projekt/BlogEngineTINProject/Models/Comment.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BlogEngineTINProject.Models
{
    public class Comment
    {
        [Required]
        public string Id { get; set; } = Guid.NewGuid().ToString();

        [Required]
        public string Author { get; set; }

        [Required, EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Content { get; set; }

        [Required]
        public DateTime PubDate { get; set; } = DateTime.UtcNow;

        public bool IsAdmin { get; set; }

        public string RenderContent()
        {
            return Content;
        }
    }
}

projekt/BlogEngineTINProject/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace BlogEngineTINProject.Models
{
    public class Post
    {
        [Required]
        public string Id { get; set; } = DateTime.UtcNow.Ticks.ToString();

        [Required]
        public string Title { get; set; }

        public string Slug { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string Content { get; set; }

        public DateTime PubDate { get; set; } = DateTime.UtcNow;

        public DateTime LastModified { get; set; } = DateTime.UtcNow;

        public bool IsPublished { get; set; } = true;

        public IList<string> Categories { get; set; } = new List<string>();

        public IList<Comment> Comments { get; } = new List<Comment>();

        public string GetLink()
        {
            return $"/blog/{Slug}/";
        }

        public string GetEncodedLink()
        {
            return $"/blog/{System.Net.WebUtility.UrlEncode(Slug)}/";
        }

        public bool AreCommentsOpen(int commentsCloseAfterDays)
        {
            return PubDate.AddDays(commentsCloseAfterDays) >= DateTime.UtcNow;
        }

        public static string CreateSlug(string title)
        {
            title = title.ToLowerInvariant().Replace(" ", "-");
            title = RemoveDiacritics(title);
            title = RemoveReservedUrlCharacters(title);

            return title.ToLowerInvariant();
        }

        private static string RemoveReservedUrlCharacters(string text)
        {
            var reservedCharacters = new[] { "!", "#", "$", "&", "'", "(", ")", "*", ",", "/", ":", ";", "=", "?", "@", "[", "]", "\"", "%", ".", "<", ">", "\\", "^", "_", "'", "{", "}", "|", "~", "`", "+" };
            return reservedCharacters.Aggregate(text, (current, chr) => current.Replace(chr, ""));
        }

        private static string RemoveDiacritics(string text)
        {
            var normalizedString = text.Normalize(NormalizationForm.FormD);
            var stringBuilder = new StringBuilder();

            foreach (var c in normalizedString)
            {
                var unicodeCategory = CharUnicodeInfo.GetUnicodeCategory(c);
                if (unicodeCategory != UnicodeCategory.NonSpacingMark)
                {
                    stringBuilder.Append(c);
                }
            }

            return stringBuilder.ToString().Normalize(NormalizationForm.FormC);
        }

        public string RenderContent()
        {
            var result = Content;
            if (!string.IsNullOrEmpty(result))
            {
                // Set up lazy loading of images/iframes
                result = result.Replace(" src=\"", " src=\"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==\" data-src=\"");

                // Youtube content embedded using this syntax: [youtube:xyzAbc123]
                var video = "<div class=\"video\"><iframe width=\"560\" height=\"315\" title=\"YouTube embed\" src=\"about:blank\" data-src=\"https://www.youtube-nocookie.com/embed/{0}?modestbranding=1&amp;hd=1&amp;rel=0&amp;theme=light\" allowfullscreen></iframe></div>";
                result = Regex.Replace(result, @"\[youtube:(.*?)\]", m => string.Format(video, m.Groups[1].Value));
            }
            return result;
        }
    }
}

projekt/BlogEngineTINProject/Controllers/BlogController.cs
using System;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Xml;
using BlogEngineTINProject.Models;
using BlogEngineTINProject.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebEssentials.AspNetCore.Pwa;

namespace BlogEngineTINProject.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blog;
        private readonly IOptionsSnapshot<Settings> _settings;
        private readonly WebManifest _manifest;

        public BlogController(IBlogService blog, IOptionsSnapshot<Settings> settings, WebManifest manifest)
        {
            _blog = blog;
            _settings = settings;
            _manifest = manifest;
        }

        [Route("/{page:int?}")]
        [OutputCache(Profile = "default")]
        public async Task<IActionResult> Index([FromRoute]int page = 0)
        {
            var posts = await _blog.GetPosts(_settings.Value.PostsPerPage, _settings.Value.PostsPerPage * page);
            ViewData["Title"] = _manifest.Name;
            ViewData["Description"] = _manifest.Description;
            ViewData["prev"] = $"/{page + 1}/";
            ViewData["next"] = $"/{(page <= 1 ? null : page - 1 + "/")}";
            return View("~/Views/Blog/Index.cshtml", posts);
        }

        [Route("/blog/category/{category}/{page:int?}")]
        [OutputCache(Profile = "default")]
        public async Task<IActionResult> Category(string category, int page = 0)
        {
            var posts = (await _blog.GetPostsByCategory(category)).Skip(_settings.Value.PostsPerPage * page).Take(_settings.Value.PostsPerPage);
            ViewData["Title"] = _manifest.Name + " " + category;
            ViewData["Description"] = $"Articles posted in the {category} category";
            ViewData["prev"] = $"/blog/category/{category}/{page + 1}/";
            ViewData["next"] = $"/blog/category/{category}/{(page <= 1 ? null : page - 1 + "/")}";
            return View("~/Views/Blog/Index.cshtml", posts);
        }
        
        [Route("/post/{slug}")]
        [HttpGet]
        public IActionResult Redirects(string slug)
        {
            return LocalRedirectPermanent($"/blog/{slug}");
        }

        [Route("/blog/{slug?}")]
        [OutputCache(Profile = "default")]
        public async Task<IActionResult> Post(string slug)
        {
            var post = await _blog.GetPostBySlug(slug);

            if (post != null)
            {
                return View(post);
            }

            return NotFound();
        }

        [Route("/blog/edit/{id?}")]
        [HttpGet, Authorize]
        public async Task<IActionResult> Edit(string id)
        {
            ViewData["AllCats"] = (await _blog.GetCategories()).ToList();

            if (string.IsNullOrEmpty(id))
            {
                return View(new Post());
            }

            var post = await _blog.GetPostById(id);

            if (post != null)
            {
                return View(post);
            }

            return NotFound();
        }

        [Route("/blog/{slug?}")]
        [HttpPost, Authorize, AutoValidateAntiforgeryToken]
        public async Task<IActionResult> UpdatePost(Post post)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", post);
            }

            post.Slug = Models.Post.CreateSlug(post.Title);

            var existing = await _blog.GetPostById(post.Id) ?? post;
            string categories = Request.Form["categories"];

            existing.Categories = categories.Split(",", StringSplitOptions.RemoveEmptyEntries).Select(c => c.Trim().ToLowerInvariant()).ToList();
            existing.Title = post.Title.Trim();
            existing.Slug = post.Slug;
            existing.IsPublished = post.IsPublished;
            existing.Content = post.Content.Trim();
            existing.Description = post.Description.Trim();

            await SaveFilesToDisk(existing);

            await _blog.SavePost(existing);

            return Redirect(post.GetEncodedLink());
        }

        private async Task SaveFilesToDisk(Post post)
        {
            var imgRegex = new Regex("<img[^>].+ />", RegexOptions.IgnoreCase | RegexOptions.Compiled);
            var base64Regex = new Regex("data:[^/]+/(?<ext>[a-z]+);base64,(?<base64>.+)", RegexOptions.IgnoreCase);

            foreach (Match match in imgRegex.Matches(post.Content))
            {
                var doc = new XmlDocument();
                doc.LoadXml("<root>" + match.Value + "</root>");

                var img = doc.FirstChild.FirstChild;
                var srcNode = img.Attributes["src"];
                var fileNameNode = img.Attributes["data-filename"];
                
                if (srcNode != null && fileNameNode != null)
                {
                    var base64Match = base64Regex.Match(srcNode.Value);
                    if (base64Match.Success)
                    {
                        byte[] bytes = Convert.FromBase64String(base64Match.Groups["base64"].Value);
                        srcNode.Value = await _blog.SaveFile(bytes, fileNameNode.Value).ConfigureAwait(false);

                        img.Attributes.Remove(fileNameNode);
                        post.Content = post.Content.Replace(match.Value, img.OuterXml);
                    }
                }
            }
        }

        [Route("/blog/deletepost/{id}")]
        [HttpPost, Authorize, AutoValidateAntiforgeryToken]
        public async Task<IActionResult> DeletePost(string id)
        {
            var existing = await _blog.GetPostById(id);

            if (existing != null)
            {
                await _blog.DeletePost(existing);
                return Redirect("/");
            }

            return NotFound();
        }

        [Route("/blog/comment/{postId}")]
        [HttpPost]
        public async Task<IActionResult> AddComment(string postId, Comment comment)
        {
            var post = await _blog.GetPostById(postId);

            if (!ModelState.IsValid)
            {
                return View("Post", post);
            }

            if (post == null || !post.AreCommentsOpen(_settings.Value.CommentsCloseAfterDays))
            {
                return NotFound();
            }

            comment.IsAdmin = User.Identity.IsAuthenticated;
            comment.Content = comment.Content.Trim();
            comment.Author = comment.Author.Trim();
            comment.Email = comment.Email.Trim();

            if (!Request.Form.ContainsKey("website"))
            {
                post.Comments.Add(comment);
                await _blog.SavePost(post);
            }

            return Redirect(post.GetEncodedLink() + "#" + comment.Id);
        }

        [Route("/blog/comment/{postId}/{commentId}")]
        [Authorize]
        public async Task<IActionResult> DeleteComment(string postId, string commentId)
        {
            var post = await _blog.GetPostById(postId);

            if (post == null)
            {
                return NotFound();
            }

            var comment = post.Comments.FirstOrDefault(c => c.Id.Equals(commentId, StringComparison.OrdinalIgnoreCase));

            if (comment == null)
            {
                return NotFound();
            }

            post.Comments.Remove(comment);
            await _blog.SavePost(post);

            return Redirect(post.GetEncodedLink() + "#comments");
        }
    }
}

projekt/BlogEngineTINProject/Views/Blog/Comments.cshtml
@using Microsoft.Extensions.Options

@model Post
@inject IOptionsSnapshot<Settings> settings

<section id="comments">
    <div class="container">
        <h2>Komentarze</h2>
        @foreach (var comment in Model.Comments)
        {
            <article id="@comment.Id" class="@(comment.IsAdmin ? "admin" : null)" itemprop="comment" itemscope itemtype="http://schema.org/Comment">
                <h3>
                    <time datetime="@comment.PubDate.ToString("s")" itemprop="datePublished">
                        <a href="#@comment.Id" title="Permalink (#@comment.Id)">@comment.PubDate.ToString("MMMM d, yyyy")</a>
                    </time>
                </h3>

                <div class="content">
                    <p itemprop="text">@comment.RenderContent()</p>
                    <span itemprop="name">@comment.Author</span>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="delete noline" asp-controller="Blog" asp-Action="DeleteComment" asp-route-postid="@Model.Id" asp-route-commentid="@comment.Id" asp-route-afrt="@ViewData["afrt"]" title="Delete the comment...">Delete...</a>
                    }
                </div>
            </article>
        }

        @if (Model.AreCommentsOpen(settings.Value.CommentsCloseAfterDays))
        {
            if (Model.Comments.Count == 0)
            {
                <p>Brak komentarzy</p>
            }

            <form method="post" asp-controller="Blog" asp-action="AddComment" asp-route-postid="@Model.Id" asp-antiforgery="false">
                <h3>Dodaj komentarz</h3>
                <br />

                <label for="content">Komentarz</label>
                <textarea id="content" name="content" rows="5" cols="100" onfocus="" required></textarea>

                <div class="details">
                    <label for="author">Nazwa</label>
                    <input id="author" name="author" required />

                    <label for="email">E-mail</label>
                    <input id="email" name="email" required />
                    <br />

                    <input type="submit" value="Dodaj komentarz" />

                    <!-- This element is being removed by site.js. It is to prevent comment spam-->
                    <input type="hidden" name="website" />
                </div>
            </form>
        }
        else
        {
            <br />
        }
    </div>
</section>

projekt/BlogEngineTINProject/Views/Blog/Edit.cshtml
@model Post
@{
    bool isNew = string.IsNullOrEmpty(Model.Title);
    ViewData["Title"] = "Edit " + (Model.Title ?? "new post");
    var host = Context.Request.Host.ToString();
    List<string> allCats = ViewData["AllCats"] as List<string> ?? new List<string>();
    allCats.Sort();
}

@section Head{
    <link rel="stylesheet" href="~/css/admin.scss" />
}

    <form method="post" id="edit" class="container" asp-controller="Blog" asp-action="UpdatePost">
        <div asp-validation-summary="All"></div>
        <input type="hidden" asp-for="@Model.Id" />

        <label asp-for="@Model.Title" class="label">Tytuł</label>
        <input asp-for="@Model.Title" required aria-describedby="desc_title" />
        <span class="desc" id="desc_title">Tytuł wpisu bloga</span>
        <br />

        <label for="categories" class="label">Tagi</label>
        <input type="text" name="selecttag" id="selecttag" aria-describedby="desc_categories" list="taglist" placeholder="@string.Join(", ", Model.Categories)"  />
        <input type="text" name="categories" id="categories" value="@string.Join(", ", Model.Categories)" hidden />
        <span class="desc" id="desc_categories">Wybierz z listy lub wpisz własne tagi, oddzielone przecinkami</span>
        <datalist id="taglist">
            @foreach (var cat in allCats)
            {
                <option value="@cat"/>
            }
            </datalist>
        <br />

        <label asp-for="@Model.Description" class="label">Opis</label>
        <textarea asp-for="@Model.Description" rows="3" aria-describedby="desc_excerpt">@Model.Description</textarea>
        <span class="desc" id="desc_excerpt">Opis tworzonego wpisu</span>
        <br />

        <textarea asp-for="@Model.Content" rows="20" aria-label="Content">@Model.Content</textarea>
        <br />

        <input type="submit" value="Zapisz" title="Save" />

        <input asp-for="@Model.IsPublished" />
        <label asp-for="@Model.IsPublished">Publikacja</label>

        @if (!isNew)
        {
            <input type="submit" value="Usuń..." class="delete" title="Usuń post..." asp-action="DeletePost" asp-route-id="@Model.Id" />
        }
    </form>

@section Scripts {
    <script src="//@host/lib/tinymce/tinymce.min.js"></script> @*with enabled CDN tinymce is not able to find some files*@
    <script src="~/js/admin.js" async></script>
}

projekt/BlogEngineTINProject/Views/Blog/Index.cshtml
@using Microsoft.Extensions.Options

@model IEnumerable<Post>
@inject IOptionsSnapshot<Settings> settings
@{
    int currentPage = int.Parse(ViewContext.RouteData.Values["page"] as string ?? "0");
}

@foreach (var post in Model)
{
    await Html.RenderPartialAsync("Post.cshtml", post);
}

<nav class="pagination container" aria-label="Pagination">
    @if (Model.Any())
    {
        <a rel="prev" href="@ViewData["prev"]" title="Previous posts"><< Poprzednie</a>
    }
    @if (currentPage > 0)
    {
        <a rel="next" href="@ViewData["next"]" title="Next posts">Następne >></a>
    }
    <br /><br />

    @section Head {
        @if (Model.Any())
        {
            <link rel="prev" href="@ViewData["prev"]" />
        }
        @if (currentPage > 0)
        {
            <link rel="next" href="@ViewData["next"]" />
        }
    }
</nav>

projekt/BlogEngineTINProject/Views/Blog/Post.cshtml
@using Microsoft.Extensions.Options

@model Post
@inject IOptionsSnapshot<Settings> settings
@{
    ViewData["Title"] = Model.Title;
    ViewData["Description"] = Model.Description;
    bool showFullPost = ViewContext.RouteData.Values.ContainsKey("slug");
    string host = Context.Request.Scheme + "://" + Context.Request.Host;
    bool isCodePreview = Model.Content.Contains("</code>");
}

@section Head {
    <link rel="canonical" href="@(host + Model.GetLink())" />
}

<article class="post container" itemscope itemtype="http://schema.org/BlogPosting" itemprop="blogPost">
    <header>
        <h1 itemprop="name headline"><a href="@Model.GetLink()" rel="canonical" itemprop="url">@Model.Title</a></h1>
        <time datetime="@Model.PubDate.ToString("s")" itemprop="datePublished">Opublikowano @Model.PubDate.ToString("MMM d, yyyy")</time>
        @if (User.Identity.IsAuthenticated)
        {
            <a asp-controller="Blog" asp-action="edit" asp-route-id="@Model.Id" title="Edytuj post">Edytuj</a>
        }
    </header>

    <div itemprop="articleBody mainEntityOfPage" cdnify>
        @Html.Raw(Model.RenderContent())
    </div>

    <footer>
        @if (Model.Categories.Any())
        {
            <ul class="categories">
                <li> Tagi: </li>
                @foreach (string cat in Model.Categories)
                {
                    <li itemprop="articleSection"><a asp-controller="Blog" asp-action="Category" asp-route-category="@cat.ToLowerInvariant()" asp-route-page="">@cat</a></li>
                }
            </ul>
            <text> </text>
        }

        <a href="@Model.GetLink()#comments" itemprop="discussionUrl" title="Go to the comments section">
            <span itemprop="commentCount">@Model.Comments.Count</span> @(Model.Comments.Count == 1 ? "komentarz" : "komentarze(y)")
        </a>

        <meta itemprop="author" content="@settings.Value.Owner" />
        <meta itemprop="dateModified" content="@Model.LastModified.ToString("s")" />
        <meta itemprop="mainEntityOfPage" content="@(host + Model.GetLink())" />
    </footer>
</article>

@if (showFullPost)
{
    await Html.RenderPartialAsync("Comments");

    @section Preload {
        @* This lazy loads the stylesheet in a non-render blocking way *@
        <link rel="preload" href="~/css/comments.scss" as="style" />
        <noscript><link rel="stylesheet" href="~/css/comments.scss" /></noscript>
        @if (isCodePreview)
        {
            <link rel="preload" href="~/lib/prism/prism.scss" as="style" />
            <script src="~/lib/prism/prism.js" async defer></script>
        }
    }
}

@if (User.Identity.IsAuthenticated)
{
    @section Scripts {
        <script src="~/js/admin.js" async defer></script>
        <link rel="stylesheet" href="~/css/admin.scss" />
    }
}